default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rodrigo_blog
  password: rodrigo_blog
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: rooood_dot_com_development

test:
  <<: *default
  database: rooood_dot_com_test

# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: <%= ENV['RODRIGO_BLOG_DB_NAME'] %>
  username: <%= ENV['RODRIGO_BLOG_DB_USERNAME'] %>
  password: <%= ENV['RODRIGO_BLOG_DB_PASSWORD'] %>
